[build-system]
build-backend = "cmeel"
requires = ["cmeel-eigen", "cmeel-libomp; sys_platform == 'darwin'", "cmeel[build]"]

[project]
dependencies = ["cmeel-libomp; sys_platform == 'darwin'"]
description = "cmeel distribution for TEASER++"
license = "MIT"
name = "cmeel-teaser-plusplus"
requires-python = ">= 3.10"
version = "2.0"

[project.urls]
homepage = "https://github.com/cmake-wheel/cmeel-teaser-plusplus"
upstream = "https://github.com/MIT-SPARK/TEASER-plusplus"

[tool.cmeel]
build-number = 0
run-tests = false
source = "TEASER-plusplus"

[tool.tomlsort]
all = true
